In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr_1d=np.array([1,2,3])
print(arr_1d)


[1 2 3]


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(arr_2d.ndim)
arr_22d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_22d)
print(arr_22d.ndim)
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(arr_3d)
print(arr_3d.ndim)

[[1 2 3]
 [4 5 6]]
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
3


In [ ]:
zero=np.zeros((2,3))
print(zero)
ones=np.ones((3,3))
print(ones)
random=np.random.randint((3,3))
print(random)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 0]


In [ ]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
b=np.arange(0,10,2)
print(b)

[0 2 4 6 8]


In [ ]:
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(arr_3d)
print(arr_3d.ndim)
print(arr_3d.shape)
print(arr_3d.size)
print(arr_3d.dtype)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
3
(2, 2, 3)
12
int64


In [ ]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)
print(temp_data.ndim)
print(temp_data.shape)
print(temp_data.size)
print(temp_data.dtype)

[[22 25 20]
 [24 26 23]]
2
(2, 3)
6
int64


In [ ]:
GH3=np.array([21, 23, 22])
print(GH3)
updated_temp_data=np.vstack([GH3,temp_data])
print(updated_temp_data)

[21 23 22]
[[21 23 22]
 [22 25 20]
 [24 26 23]]


In [ ]:
sensor_error_flags=np.zeros([2,3])
print(sensor_error_flags)
sensor_error_flags1=np.zeros((2,3))
print(sensor_error_flags1)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
greenhouse_identity=np.eye(3)
print(greenhouse_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(updated_temp_data)
print(updated_temp_data[:,1:])
print(updated_temp_data[:,:])

[[21 23 22]
 [22 25 20]
 [24 26 23]]
[[23 22]
 [25 20]
 [26 23]]
[[21 23 22]
 [22 25 20]
 [24 26 23]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.

The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array

Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.


In [ ]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments[0,2:3])

[55]


In [ ]:
#  Oranges shipped on Sunday
print(shipments[1,6])

75


In [ ]:
print(shipments[:,0:5])

[[50 60 55 70 65]
 [40 45 50 60 55]]


In [ ]:
print("Extract only the weekend shipments (Sat & Sun)")
print(shipments[:,5:])

Extract only the weekend shipments (Sat & Sun)
[[80 90]
 [70 75]]


In [ ]:
print("Extract the shipments of Apples from Wednesday to Saturday.")
print(shipments[0,2:-1])

Extract the shipments of Apples from Wednesday to Saturday.
[55 70 65 80]


In [ ]:
print("Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.")
shipments[0:5,6]=100
shipments[1:5,6]=75
print(shipments)

Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.
[[ 50  60  55  70  65  80 100]
 [ 40  45  50  60  55  70  75]]


In [ ]:
mat1=np.array([[1,2],[4,5]])
mat2=np.array([[7,8],[10,11]])
print(mat1)
print(mat2)
print(mat1+mat2)
print(mat1*mat2)
print(np.dot(mat1,mat2))

[[1 2]
 [4 5]]
[[ 7  8]
 [10 11]]
[[ 8 10]
 [14 16]]
[[ 7 16]
 [40 55]]
[[27 30]
 [78 87]]


In [ ]:
#universal functions
arr=np.array([1,2,3])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.power(arr,2))
print(np.exp(arr)-1)
print(np.expm1(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[1 4 9]
[ 1.71828183  6.3890561  19.08553692]
[ 1.71828183  6.3890561  19.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [ ]:
farmA=np.array([[10,12,13],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all=np.stack([farmA,farmB,farmC])
print(production_all)

[[[10 12 13]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]


In [ ]:
print(production_all.ndim)
print(production_all.shape)
print(production_all.size)
print(production_all.dtype)

3
(3, 4, 3)
36
int64


In [78]:
total_per_farm = np.sum(production_all, axis=(1, 2))

mean_per_farm = np.mean(production_all, axis=(1, 2))
std_per_farm = np.std(production_all, axis=(1, 2))
var_per_farm = np.var(production_all, axis=(1, 2))

print("Total per farm:", total_per_farm)
print("Mean per farm:", mean_per_farm)
print("Std per farm:", std_per_farm)
print("Var per farm:", var_per_farm)


Total per farm: [128 234 174]
Mean per farm: [10.66666667 19.5        14.5       ]
Std per farm: [2.09496751 1.97905701 1.97905701]
Var per farm: [4.38888889 3.91666667 3.91666667]


In [ ]:


# Per-hour matrix multiplication idea (matrix op)
# For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
# Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)

hour_weights = np.array([0.5, 1.0, 0.75])

weighted_per_panel = np.array([np.dot(farm, hour_weights) for farm in production_all])
print("Weighted per panel (each farm):\n", weighted_per_panel)


Weighted per panel (each farm):
 [[26.75 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]


In [68]:
production_all[1] = production_all[1].astype(float) + 0.5
print("After calibration offset (Farm B):\n", production_all[1])

After calibration offset (Farm B):
 [[20 19 21]
 [18 20 19]
 [22 23 21]
 [17 18 16]]


In [69]:
# reshape means and stds for broadcasting
means = mean_per_farm.reshape(3, 1, 1)
stds = std_per_farm.reshape(3, 1, 1)

normalized = (production_all - means) / stds
print("Normalized data (first farm):\n", normalized[0])


Normalized data (first farm):
 [[-0.31822291  0.63644583  1.1137802 ]
 [-0.79555728  0.15911146 -0.31822291]
 [ 0.63644583  1.1137802   1.59111457]
 [-1.27289165 -1.75022603 -0.79555728]]


In [70]:
exp_data = np.exp(normalized)
expm1_data = np.expm1(normalized)

# To avoid log on negative/zero values, shift
log_data = np.log(np.abs(normalized) + 1)
log10_data = np.log10(np.abs(normalized) + 1)
log2_data = np.log2(np.abs(normalized) + 1)

sin_data = np.sin(normalized)
cos_data = np.cos(normalized)
tan_data = np.tan(normalized)

arcsin_data = np.arcsin(np.clip(np.tanh(normalized), -1, 1))  # safe mapping
arccos_data = np.arccos(np.clip(np.tanh(normalized), -1, 1))
arctan_data = np.arctan(normalized)

deg_data = np.degrees(normalized)
rad_data = np.radians(normalized)

round_data = np.round(normalized)
floor_data = np.floor(normalized)
ceil_data = np.ceil(normalized)
trunc_data = np.trunc(normalized)


In [71]:
high_output = production_all > 20

# Example extra mask: even hour index (hours 0,2)
even_hours_mask = np.arange(3) % 2 == 0
even_hours_mask = even_hours_mask.reshape(1, 1, 3)

high_and_even = np.logical_and(high_output, even_hours_mask)
high_or_even = np.logical_or(high_output, even_hours_mask)
not_high = np.logical_not(high_output)
xor_mask = np.logical_xor(high_output, even_hours_mask)

ge_mask = np.greater_equal(production_all, 20)
less_mask = np.less(production_all, 10)


In [73]:
alerts = np.array([
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]],
    [[1,0,1],[0,0,1],[1,1,0],[0,1,0]]
], dtype=int)
print(np.bitwise_and(alerts, (production_all.astype(int) % 2)))

bit_or = np.bitwise_or(alerts, (production_all.astype(int) % 2))
bit_invert = np.invert(alerts)


[[[0 0 1]
  [0 0 0]
  [0 1 0]
  [0 1 0]]

 [[0 0 1]
  [0 0 1]
  [0 1 0]
  [0 0 0]]

 [[1 0 0]
  [0 0 1]
  [0 1 0]
  [0 1 0]]]


In [74]:
added = np.add(normalized, 2)
subtracted = np.subtract(normalized, 1)
multiplied = np.multiply(normalized, 3)
divided = np.divide(normalized, 2)
powered = np.power(normalized, 2)
modded = np.mod(normalized, 2)


In [75]:
sum_exp = np.sum(exp_data)
mean_sin = np.mean(sin_data)
print("Sum(exp):", sum_exp)
print("Mean(sin):", mean_sin)


Sum(exp): 57.13549350970219
Mean(sin): 0.004097154898017313


In [76]:
panel_totals_per_farm = np.sum(production_all, axis=2)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)

print("Panel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance:", needs_maintenance)


Panel totals per farm:
 [[35 30 39 24]
 [60 57 66 51]
 [45 42 51 36]]
Needs maintenance: [ True False  True]


In [77]:
overall_total = np.sum(production_all)

# Peak hour
peak_value = np.max(production_all)
peak_index = np.unravel_index(np.argmax(production_all), production_all.shape)
peak_farm, peak_panel, peak_hour = peak_index

average_per_panel = np.mean(production_all, axis=(0, 2))

print("Overall total:", overall_total)
print(f"Peak value {peak_value} at Farm {peak_farm}, Panel {peak_panel}, Hour {peak_hour}")
print("Average per panel across all farms:", average_per_panel)


Overall total: 536
Peak value 23 at Farm 1, Panel 2, Hour 1
Average per panel across all farms: [15.55555556 14.33333333 17.33333333 12.33333333]


In [83]:
arr1=np.array([1,2,3,4,5,6])
print("Reshape array",np.reshape(arr1,(2,3)))

Reshape array [[1 2 3]
 [4 5 6]]


In [84]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print("Stack arrays vertically",np.vstack((arr1,arr2)))
print("Stack arrays horizontally",np.hstack((arr1,arr2)))

Stack arrays vertically [[1 2 3 4]
 [5 6 7 8]]
Stack arrays horizontally [1 2 3 4 5 6 7 8]


In [85]:
print("Spliting array",np.array_split(arr1,3))

Spliting array [array([1, 2]), array([3]), array([4])]


In [86]:
a1=np.array([1,2,3,4,5,6,7,8])
indices=[0,2]
print(a1[indices])

[1 3]


In [87]:
view=a1.view()
view[2]=10
print(a1," ",view)

[ 1  2 10  4  5  6  7  8]   [ 1  2 10  4  5  6  7  8]


In [89]:
copy=a1.copy()
copy[2]=30
print(a1," ",copy)

[ 1  2 10  4  5  6  7  8]   [ 1  2 30  4  5  6  7  8]


In [91]:
arr=np.array([1,2,3,4])
np.save("arr.npy",arr)

In [92]:
print(np.load("arr.npy"))

[1 2 3 4]


In [93]:
arr1=np.arange(10,51)
print(arr1)
#Create a 3x3 array of random numbers between 0 and 1.
arr2=np.random.rand(3,3)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.79210907 0.49865634 0.30361359]
 [0.33514155 0.84394474 0.29145697]
 [0.87511065 0.45416216 0.71026906]]


In [94]:
# Add 5 to every element of a 1D array.
arr3=np.array([1,2,3,4,5])
print(arr3+5)

arr_2d=np.array([[1,2,3],[4,5,6]])
arr_2d2=np.array([[1,2,3],[1,1,1]])
print(arr_2d*arr_2d2)


[ 6  7  8  9 10]
[[1 4 9]
 [4 5 6]]


In [95]:
#Create a 5x5 array of integers from 1 to 25.
a=np.random.randint(1,26,size=(5,5))
print(a)

[[14 15  1  9 16]
 [ 5 13 24 20 25]
 [24  8 22  3 23]
 [12 22  3 11  8]
 [17  9 11 18 24]]


In [104]:
print(a[:1])
#The last column.
print(a[:,-1])

[[14 15  1  9 16]]
[16 25 23  8 24]


In [105]:
print(a[:3])

[[14 15  1  9 16]
 [ 5 13 24 20 25]
 [24  8 22  3 23]]


In [113]:
print(a[:,-2:])

[[ 9 16]
 [20 25]
 [ 3 23]
 [11  8]
 [18 24]]


In [118]:
#A subarray of the first three rows and first two columns.
print(a[:3,:2])



[[14 15]
 [ 5 13]
 [24  8]]


In [124]:
b=np.random.randint(10,100,size=(1,10))
print(b)

[[31 23 33 64 59 83 77 44 53 82]]


In [129]:
c=np.ones((3,3),dtype=int)
print(c)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [130]:
d=[1, 2, 3]
print(c+d)

[[2 3 4]
 [2 3 4]
 [2 3 4]]


In [132]:
e=np.arange(1,50)
print(e)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [133]:
print(e[e%5==0])

[ 5 10 15 20 25 30 35 40 45]
